# Generated by Django 3.2.9 on 2022-02-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=599, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('board', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(blank=True, max_length=40)),
                ('Exam_name', models.CharField(max_length=1000)),
                ('details', models.TextField()),
                ('Exam_start_time', models.CharField(max_length=60)),
                ('Exam_start_date', models.DateField()),
                ('Exam_end_time', models.CharField(max_length=60)),
                ('Exam_end_date', models.DateField()),
                ('exam_total_time', models.IntegerField(default=10)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam_cover_photos')),
                ('level', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('total_mark', models.FloatField(blank=True, max_length=400, null=True)),
                ('pass_mark', models.FloatField(blank=True, max_length=400, null=True)),
                ('mark_per_question', models.FloatField(blank=True, max_length=400, null=True)),
                ('isRandomized', models.BooleanField(default=False, verbose_name='Randomization')),
                ('isSorted', models.BooleanField(default=False, verbose_name='Sorting')),
                ('isNegativeMarking', models.BooleanField(default=False, verbose_name='Negative Marking')),
                ('amount_per_mistake', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Amount per mistake')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamPack_name', models.CharField(max_length=1000, verbose_name='Exam Pack Name')),
                ('pack_image', models.ImageField(blank=True, null=True, upload_to='pack_image')),
                ('details', models.TextField()),
                ('batch', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('question_name', models.TextField(blank=True, max_length=4000, null=True)),
                ('Q_image', models.ImageField(blank=True, null=True, upload_to='Question_img')),
                ('data_one', models.CharField(blank=True, max_length=3000, null=True)),
                ('data_two', models.CharField(blank=True, max_length=3000, null=True)),
                ('data_three', models.CharField(blank=True, max_length=3000, null=True)),
                ('data_four', models.CharField(blank=True, max_length=3000, null=True)),
                ('marks', models.IntegerField(default=4)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_examTwo', to='Exam_Dashboard.createexam')),
                ('exam_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel_Three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_description', models.TextField(max_length=500)),
                ('question_name', models.TextField(blank=True, max_length=500, null=True)),
                ('question_one_ans_one', models.TextField(blank=True, max_length=500, null=True)),
                ('question_one_ans_one_is_correct', models.BooleanField(default=False)),
                ('question_one_ans_two', models.CharField(blank=True, max_length=500, null=True)),
                ('question_one_ans_two_is_correct', models.BooleanField(default=False)),
                ('question_one_ans_three', models.CharField(blank=True, max_length=500, null=True)),
                ('question_one_ans_three_is_correct', models.BooleanField(default=False)),
                ('question_one_ans_four', models.CharField(blank=True, max_length=500, null=True)),
                ('question_one_ans_four_is_correct', models.BooleanField(default=False)),
                ('q_image', models.ImageField(blank=True, null=True, upload_to='Question_img')),
                ('question_name_two', models.TextField(blank=True, max_length=400, null=True)),
                ('sample_one', models.TextField(blank=True, max_length=400, null=True)),
                ('sample_two', models.TextField(blank=True, max_length=400, null=True)),
                ('sample_three', models.TextField(blank=True, max_length=400, null=True)),
                ('question_two_ans_one', models.CharField(blank=True, max_length=500, null=True)),
                ('question_two_ans_one_is_correct', models.BooleanField(default=False)),
                ('question_two_ans_two', models.CharField(blank=True, max_length=500, null=True)),
                ('question_two_ans_two_is_correct', models.BooleanField(default=False)),
                ('question_two_ans_three', models.CharField(blank=True, max_length=500, null=True)),
                ('question_two_ans_three_is_correct', models.BooleanField(default=False)),
                ('question_two_ans_four', models.CharField(blank=True, max_length=500, null=True)),
                ('question_two_ans_four_is_correct', models.BooleanField(default=False)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_examThree', to='Exam_Dashboard.createexam')),
                ('exam_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField(max_length=4000, unique=True)),
                ('q_image', models.ImageField(blank=True, null=True, upload_to='Question_img')),
                ('marks', models.IntegerField(default=4)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_exam', to='Exam_Dashboard.createexam')),
                ('exam_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack')),
            ],
        ),
        migrations.AddField(
            model_name='createexam',
            name='exam_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack', to='Exam_Dashboard.exampack'),
        ),
        migrations.CreateModel(
            name='AnswerModel_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=3000)),
                ('is_correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='Exam_Dashboard.questionmodel_one')),
            ],
        ),
        migrations.CreateModel(
            name='AnsModel_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=400)),
                ('is_correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_two', to='Exam_Dashboard.questionmodel_two')),
            ],
        ),
    ]
