# Generated by Django 3.2.9 on 2021-12-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('details', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam_cover_photos')),
                ('level', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('total_mark', models.IntegerField(default=0)),
                ('pass_mark', models.IntegerField(default=0)),
                ('mark_per_question', models.IntegerField(default=1)),
                ('isRandomized', models.BooleanField(default=False, verbose_name='Randomization')),
                ('isSorted', models.BooleanField(default=False, verbose_name='Sorting')),
                ('isNegativeMarking', models.BooleanField(default=False, verbose_name='Negative Marking')),
                ('amount_per_mistake', models.IntegerField(default=0, verbose_name='Amount per mistake')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Exam Pack Name')),
                ('details', models.TextField()),
                ('batch', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam_pack_cover_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(max_length=1000)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='question_bank')),
                ('exam_type', models.CharField(choices=[('type 1', 'type 1'), ('type 2', 'type 2'), ('type 3', 'type 3')], max_length=30)),
                ('op_1', models.CharField(max_length=200, null=True)),
                ('op_2', models.CharField(max_length=200, null=True)),
                ('op_3', models.CharField(max_length=200, null=True)),
                ('op_4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exammodel')),
            ],
        ),
        migrations.AddField(
            model_name='exammodel',
            name='exam_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack', to='Exam_Dashboard.exampack'),
        ),
    ]
