# Generated by Django 3.2.9 on 2022-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='amount_per_mistake',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount per mistake'),
        ),
    ]
