# Generated by Django 3.2.9 on 2021-12-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExam_Panel', '0001_initial'),
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamModel',
            new_name='CreateExam',
        ),
    ]
