# Generated by Django 3.2.9 on 2021-12-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_model_one',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_model_one',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_model_three',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_model_three',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_model_two',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_model_two',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
    ]
