# Generated by Django 3.2.9 on 2021-12-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createexam',
            name='exam_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quesionmodel_three',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_examThree', to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quesionmodel_three',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel_one',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_exam', to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel_one',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel_two',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_examTwo', to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel_two',
            name='exam_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exampack'),
            preserve_default=False,
        ),
    ]
