# Generated by Django 3.2.9 on 2022-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createexam',
            name='exam_total_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='questionmodel_one',
            name='marks',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='questionmodel_three',
            name='marks',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel_two',
            name='marks',
            field=models.IntegerField(default=4),
        ),
    ]
