# Generated by Django 3.2.9 on 2021-12-18 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('73b2ecac-0e96-45d1-be3b-23cdddba73f6'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exam_Dashboard.basemodel')),
                ('question_name', models.CharField(max_length=4000)),
                ('marks', models.IntegerField(default=5)),
            ],
            bases=('Exam_Dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exam_Dashboard.basemodel')),
                ('Answer', models.CharField(max_length=3000)),
                ('is_correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='Exam_Dashboard.questionmodel')),
            ],
            bases=('Exam_Dashboard.basemodel',),
        ),
    ]
