# Generated by Django 3.2.9 on 2021-12-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='exam',
        ),
        migrations.DeleteModel(
            name='CreateExam',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
