# Generated by Django 3.2.9 on 2022-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0002_auto_20220102_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=599, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('board', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
