# Generated by Django 3.2.9 on 2021-12-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0002_ansmodel_three_ansmodel_two_answermode_one_quesionmodel_three_questionmodel_one_questionmodel_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='Q_Description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='Q_image',
            field=models.ImageField(default=1, upload_to='Question_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='Q_one',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_one',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_three',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_two',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
