# Generated by Django 3.2.9 on 2022-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0002_alter_createexam_amount_per_mistake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='mark_per_question',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='pass_mark',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='total_mark',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
