# Generated by Django 3.2.9 on 2021-12-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0002_rename_exammodel_createexam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createexam',
            old_name='name',
            new_name='ExamPack_name',
        ),
    ]
