# Generated by Django 3.2.9 on 2021-12-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0003_auto_20211220_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='Q_image',
            field=models.ImageField(blank=True, null=True, upload_to='Question_img'),
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='Q_one',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='marks',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_one',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_three',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='quesionmodel_three',
            name='sample_two',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
