# Generated by Django 3.2.9 on 2022-01-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0003_batchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='Exam_end_time',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='Exam_start_time',
            field=models.CharField(max_length=60),
        ),
    ]
