# Generated by Django 3.2.9 on 2022-01-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0003_auto_20220123_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='amount_per_mistake',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Amount per mistake'),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='mark_per_question',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='pass_mark',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='total_mark',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
    ]
