# Generated by Django 3.2.9 on 2021-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0003_createexam_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createexam',
            name='time',
            field=models.TimeField(default='auto'),
        ),
    ]
