# Generated by Django 3.2.9 on 2022-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0004_auto_20220111_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel_two',
            name='Q_image',
            field=models.ImageField(blank=True, null=True, upload_to='Question_img'),
        ),
    ]
