# Generated by Django 3.2.9 on 2021-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0004_auto_20211208_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
