# Generated by Django 3.2.9 on 2022-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0005_alter_questionmodel_two_q_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel_two',
            name='data_four',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
