# Generated by Django 3.2.9 on 2021-12-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0005_alter_createexam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='amount_per_mistake',
            field=models.FloatField(default=0, verbose_name='Amount per mistake'),
        ),
    ]
