# Generated by Django 3.2.9 on 2022-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0006_questionmodel_two_data_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createexam',
            name='amount_per_mistake',
            field=models.CharField(max_length=50, verbose_name='Amount per mistake'),
        ),
    ]
