# Generated by Django 3.2.9 on 2022-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0007_alter_createexam_amount_per_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel_three',
            name='question_name_two',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
