# Generated by Django 3.2.9 on 2022-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0008_questionmodel_three_question_name_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel_three',
            name='question_name_two',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
