# Generated by Django 3.2.9 on 2022-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_ExamDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='negative_marking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(default=0, max_length=400),
        ),
    ]
