# Generated by Django 3.2.9 on 2022-01-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_ExamDashboard', '0002_auto_20220101_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
