# Generated by Django 3.2.9 on 2022-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_ExamDashboard', '0002_auto_20220113_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
