# Generated by Django 3.2.9 on 2022-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_ExamDashboard', '0004_alter_examresult_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=550, null=True)),
                ('board', models.CharField(blank=True, max_length=550, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=550, null=True)),
                ('score', models.CharField(blank=True, max_length=550, null=True)),
                ('negative_marking', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
    ]
