# Generated by Django 3.2.9 on 2022-01-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0002_auto_20220102_1602'),
        ('Student_ExamDashboard', '0005_allstudentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudentresult',
            name='exam_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.createexam'),
            preserve_default=False,
        ),
    ]
