# Generated by Django 3.2.9 on 2022-01-12 13:49

import Login_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_ExamDashboard', '0006_allstudentresult_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudentresult',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='', verbose_name=Login_App.models.StudentProfile),
            preserve_default=False,
        ),
    ]
