# Generated by Django 3.2.9 on 2022-01-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login_App.userinfo'),
            preserve_default=False,
        ),
    ]
