# Generated by Django 3.2.9 on 2021-12-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='StudentImage'),
            preserve_default=False,
        ),
    ]
