# Generated by Django 3.2.9 on 2022-01-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_studentprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
    ]
