# Generated by Django 3.2.9 on 2022-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(upload_to='Student_Profile'),
        ),
    ]
