# Generated by Django 3.2.9 on 2022-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_remove_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
