# Generated by Django 3.2.9 on 2022-01-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0005_alter_studentprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='image',
            new_name='Profile_image',
        ),
    ]
