# Generated by Django 3.2.9 on 2022-01-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0006_rename_image_studentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Student_Profile'),
        ),
    ]
